"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
import { Head } from 'next/document'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const client = new ApolloClient({

  uri: 'http://localhost:3050/graphql',

  cache: new InMemoryCache(),

});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloProvider client={client}>

    <html lang="en">
        <title>Social-Media-Clone</title>
      <body className={inter.className}>{children}</body>
    </html>
    </ApolloProvider>

  )
}
