import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
const inter = Inter({ subsets: ['latin'] })
const client = new ApolloClient({
  uri: 'http://localhost:3050/graphql',
  cache: new InMemoryCache(),
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloProvider client={client}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ApolloProvider>
  )
}
